# Generated by Django 3.2.5 on 2021-10-09 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitegate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=128, unique=True, verbose_name='dummy')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('time_accepted', models.DateTimeField(editable=False, null=True, verbose_name='Date accepted')),
                ('remote', models.CharField(db_index=True, max_length=20, verbose_name='Remote alias')),
                ('remote_id', models.CharField(db_column='rid', null=True, default=None, db_index=True, max_length=64, verbose_name='Remote ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remotes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Remote record',
                'verbose_name_plural': 'Remotes records',
            },
        ),
    ]
